meta          :
  title       : Windtoday
  description : windtoday is windsurfing marketplace to discover, compare & choose daily equipment offers. Pay and receive it at home, independently where you are.
  logoImage   : https://blog.windtoday.co/logo.png
  ogImage     : https://blog.windtoday.co/cover.jpg
  twitter     : '@windtodayco'
  url         : https://windtoday.co

algolia       :
  appId       : PDZK7H6PD0
  apiKey      : 911167d1e62d76e16e9cd746c0b1a684
  indexName   : windsurf
